# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyecoordinate',
            name='face_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_coordinates', to='api.FaceImage'),
        ),
        migrations.AlterField(
            model_name='mouthcoordinate',
            name='face_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouth_coordinates', to='api.FaceImage'),
        ),
        migrations.AlterField(
            model_name='nosecoordinate',
            name='face_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nose_coordinates', to='api.FaceImage'),
        ),
    ]
