# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 02:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160708_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('face_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_coordinates', to='api.FaceImage')),
            ],
        ),
    ]
